In [1]:
import numpy as np

In [2]:
arr = np.array([1, 3, 6])

In [3]:
# numpy.arange([başlat, ]durdur, [adım, ]dtype=Yok, *, like=Yok)
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [4]:
# numpy.zeros(shape, dtype=float, order='C', *, like=Yok)
np.zeros(shape=(10, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [5]:
# numpy.ones(shape, dtype=Yok, sipariş='C', *, like=Yok)
np.ones(shape=(10, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [6]:
np.random.seed(101)
# random.randint(düşük, yüksek=Yok, boyut=Yok, dtype=int)
arr = np.random.randint(0, 100, 10)
arr

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [7]:
arr.max()

95

In [8]:
# numpy.argmax(a, axis=Yok, out=Yok, *, keepdims=<değer yok>)
# Bir eksen boyunca maksimum değerlerin indekslerini döndürür.
arr.argmax()

0

In [9]:
arr.argmin()

7

In [10]:
arr.mean()

60.8

In [11]:
arr.reshape((2,5))

array([[95, 11, 81, 70, 63],
       [87, 75,  9, 77, 40]])

In [12]:
# np.linspace(10.0, 10.0, sayı=25).reshape((5,5))

np.full(shape=(5,5), fill_value=10.0)

array([[10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.]])